# Global system configuration
language: android
sudo: false
jdk: oraclejdk7
os:
  - linux  

# Define environment variables
env:
  matrix:
    # Uncomment to use
    - ANDROID_SDKS=android-23 ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a SYS_IMG_TARGET=android-23 SYS_IMGE_ABI=armeabi-v7a
    # - ANDROID_SDKS=android-21 ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a SYS_IMG_TARGET=android-21 SYS_IMGE_ABI=armeabi-v7a
    # - ANDROID_SDKS=android-20 ANDROID_TARGET=android-20 ANDROID_ABI=android-wear/armeabi-v7a SYS_IMG_TARGET=android-wear-20, SYS_IMGE_ABI=armeabi-v7a
    # - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a SYS_IMG_TARGET=android-19 SYS_IMGE_ABI=armeabi-v7a
    # - ANDROID_SDKS=android-16 ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a SYS_IMG_TARGET=android-16 SYS_IMGE_ABI=armeabi-v7a
    # - ANDROID_SDKS=android-14 ANDROID_TARGET=android-14 ANDROID_ABI=armeabi-v7a SYS_IMG_TARGET=android-14 SYS_IMGE_ABI=armeabi-v7a
  global:
    # Wait up to 10 minutes for adb to connect to the emulator
    - ADB_INSTALL_TIMEOUT=10

# Configure the cache
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/caches/2.10
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  # All components are listed using 
  # android list sdk --no-ui --all --extended
  components:
    # Android SDK Tools
    - tools
    - platform-tools

    # The Build Tools version used by the project
    - build-tools-23.0.3

    # The SDK version used to compile the project
    - android-23

    # Uncomment to use
    # - android-21
    # - android-20
    # - android-19
    # - android-16
    # - android-14

    # Additional components
    - extra                                 # Google extras
    - extra-google-m2repository             # Maven Google repo
    - extra-android-m2repository            # Maven Android repo
    - extra-android-support                 # Android Support Library
    - addon-google_apis-google-23           # Google APIs 23
    - extra-google-webdriver                # Web device driver

    # System images required for building the project
    - sys-img-${SYS_IMGE_ABI}-${SYS_IMG_TARGET}

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  # Uncomment to use
  # - ./gradlew jacocoTestReport
  - android-wait-for-emulator
  - adb devices
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck
  - ./gradlew connectedAndroidTest

# Uncomment to use
# after_success:
  # - echo "Success!"

# Uncomment to use
# after_failure:
  # - echo "Failed!"

# Uncomment to use
# after_script:
  # - echo "Finished."